// Generated by https://quicktype.io

using Newtonsoft.Json;

namespace KubernetesStats.Models
{
    public class ServerInfo
    {
        [JsonProperty("kind")]
        public string Kind { get; set; }

        [JsonProperty("versions")]
        public string[] Versions { get; set; }

        [JsonProperty("serverAddressByClientCIDRs")]
        public ServerAddressByClientCidr[] ServerAddressByClientCidRs { get; set; }
    }

    public class ServerAddressByClientCidr
    {
        [JsonProperty("clientCIDR")]
        public string ClientCidr { get; set; }

        [JsonProperty("serverAddress")]
        public string ServerAddress { get; set; }
    }

    public class TopLevel
    {
        public static TopLevel FromJson(string json) => JsonConvert.DeserializeObject<TopLevel>(json, Converter.Settings);
    }
}